<?php

/*
 * This file is part of the LibbitKerberosBundle package.
 *
 * (c) RedNose <info@rednose.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Libbit\KerberosBundle\Security\Authentication\Token;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-31 at 12:52:54.
 */
class KerberosTokenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KerberosToken
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new KerberosToken(null, 'test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testTokenWithoutUser()
    {
        new KerberosToken(null, 'test');
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testTokenWithoutProviderKey()
    {
        $user = new \Symfony\Component\Security\Core\User\User('test', 'test');

        new KerberosToken($user, null);
    }

    /**
     * @covers Libbit\KerberosBundle\Security\Authentication\Token\KerberosToken::getCredentials
     * @todo   Implement testGetCredentials().
     */
    public function testGetCredentials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Libbit\KerberosBundle\Security\Authentication\Token\KerberosToken::getProviderKey
     * @todo   Implement testGetProviderKey().
     */
    public function testGetProviderKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
